version: 0.1
phases:
    install:
        commands:
            - 'touch .npmignore'
            - 'npm install -g gatsby'
    pre_build:
        commands:
            - 'npm --version'
            - echo ${STAGE}
        #    - 'npm ci --production'
            - 'npm install'        
    build:
        commands:
            - 'npm run build:${STAGE}'
    post_build:
        commands:
            - 'npm run deploy'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/*'
        - 'node_modules/*'
        - 'public/*'
